
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Abrish
 */
public class phoneBill extends javax.swing.JFrame {

    /**
     * Creates new form phoneBill
     */
    public phoneBill() {
        initComponents();
        Connect();
    }

    ResultSet rs;
    Connection con;

    public Connection Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/userreg", "root", "");

        } catch (Exception e) {
            System.out.println(e);
        }
        return con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billNo3 = new javax.swing.JTextField();
        pkg = new javax.swing.JComboBox<>();
        billNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        billNo1 = new javax.swing.JTextField();
        min = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        billNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billNo3ActionPerformed(evt);
            }
        });

        pkg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Weekly", "Monthly", "Yearly" }));

        jLabel5.setText("Packages");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(400, 250));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Phone Bill Payment");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 34, -1, -1));

        jLabel2.setText("Billing Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 103, -1, -1));

        jLabel3.setText("Packages in min");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 157, -1, -1));

        billNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billNo1ActionPerformed(evt);
            }
        });
        getContentPane().add(billNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 134, -1));

        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });
        getContentPane().add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 154, 134, -1));

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 194, 134, -1));

        jLabel6.setText("Total Price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 194, -1, 22));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jButton2.setText("Buy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NNN.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 670, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void billNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billNo1ActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        // TODO add your handling code here:
        // String Min = min.getText();
        // double mn = Double.parseDouble(Min);
        // double pr = (mn * 0.5);
        // price.setText(String.valueOf(pr));
        double pr = 0;
        double minute = Double.parseDouble(min.getText());
        if (minute < 150) {
            pr = (minute * 0.2);
            price.setText(String.valueOf(pr));
        } else if (minute < 500) {
            pr = (minute * 0.25);
            price.setText(String.valueOf(pr));
        } else {
            pr = (minute * 0.3);
            price.setText(String.valueOf(pr));
        }

    }//GEN-LAST:event_minActionPerformed

    private void billNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billNo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billNo3ActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String BillNo = billNo1.getText();
        String Price;
        double dep = 0;
        double minute = Double.parseDouble(min.getText());
        //double mn = Double.parseDouble(Min);
        double pr;
        try {
            PreparedStatement pst = con.prepareStatement("select balance from phone where billingnumber=?");
            pst.setString(1, BillNo);
            rs = pst.executeQuery();
            if (rs.next()) {
                dep = Double.parseDouble(rs.getString("balance"));
                if (minute < 150) {
                    pr = (minute * 0.2);
                } else if (minute < 500) {
                    pr = (minute * 0.25);
                } else {
                    pr = (minute * 0.3);
                }

                if (dep < pr) {
                    JOptionPane.showMessageDialog(null, "Sorry You Don't Have Enough Deposit.....");
                    min.setText("");
                    price.setText("");
                } else {
                    price.setText(String.valueOf(pr));
                    dep = dep - pr;
                }
            }

            PreparedStatement pst1 = con.prepareStatement("update phone set balance=? where billingnumber=?");

            String st = String.valueOf(dep);

            pst1.setString(1, st);
            pst1.setString(2, BillNo);
            int i = pst1.executeUpdate();
            if(i==1)
                JOptionPane.showMessageDialog(rootPane, "You've successfully bought a voice package");
            

            PreparedStatement pst2 = con.prepareStatement("update phone set price=? where billingnumber=?");

            pst2.setString(1, price.getText());
            pst2.setString(2, BillNo);
            pst2.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(phoneBill.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new phoneBill().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField billNo;
    private javax.swing.JTextField billNo1;
    private javax.swing.JTextField billNo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField min;
    private javax.swing.JComboBox<String> pkg;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
