
import com.mysql.cj.protocol.Resultset;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Abrish
 */
public class registration extends javax.swing.JFrame {

    /**
     * Creates new form registration
     */
    public registration() {
        initComponents();
        Connect();

    }

    Connection con;
    PreparedStatement pst;
    Resultset rs;

    public void Connect() {
        try {
            //Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/userreg", "root", "");

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        billNo = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        gotologin = new javax.swing.JButton();
        chooser = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        deposit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(500, 240));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 28, -1, -1));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 86, -1, -1));

        jLabel3.setText("Billing Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 215, -1, -1));

        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 295, -1, -1));

        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 255, -1, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 83, 150, -1));

        billNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billNoActionPerformed(evt);
            }
        });
        getContentPane().add(billNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 212, 150, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 252, 150, -1));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 292, 150, -1));

        register.setBackground(new java.awt.Color(0, 255, 255));
        register.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 361, -1, -1));

        cancel.setBackground(new java.awt.Color(0, 255, 255));
        cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 361, -1, -1));

        jLabel6.setText("Username");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 135, -1, -1));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 132, 150, -1));

        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 175, -1, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 172, 150, -1));

        gotologin.setText("Goto Login Page");
        gotologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotologinActionPerformed(evt);
            }
        });
        getContentPane().add(gotologin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        chooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phone", "Electric/Water" }));
        chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserActionPerformed(evt);
            }
        });
        getContentPane().add(chooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel8.setText("Deposit");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));
        getContentPane().add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 150, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NNN.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1400, 0, 1930, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void billNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billNoActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        String Name = name.getText();
        String Username = username.getText();
        String Password = password.getText();
        String BillNo = billNo.getText();
        String Email = email.getText();
        String Address = address.getText();
        String Deposit = deposit.getText();

        try {
            PreparedStatement ps = (PreparedStatement) con.prepareStatement("select * from registertable where billingnumber=?");
            ps.setString(1, BillNo);
            ResultSet resu = ps.executeQuery();
            if (resu.next()) {
                JOptionPane.showMessageDialog(rootPane, "duplicate");
                billNo.setText(null);
            } else {
                try {
                    pst = con.prepareStatement("INSERT INTO registertable(name, username, password, billingnumber, email, address) VALUES(?,?,?,?,?,?)");
                    pst.setString(1, Name);
                    pst.setString(2, Username);
                    pst.setString(3, Password);
                    pst.setString(4, BillNo);
                    pst.setString(5, Email);
                    pst.setString(6, Address);

                    int k = pst.executeUpdate();
                    if (k == 1) {
                        JOptionPane.showMessageDialog(rootPane, "You have successfully registered");
                        name.setText(null);
                        username.setText(null);
                        password.setText(null);
                        billNo.setText(null);
                        email.setText(null);
                        address.setText(null);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Failed");
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }

                String Choose = chooser.getSelectedItem().toString();
                if (Choose.equals("Phone")) {
                    try {
                        pst = con.prepareStatement("INSERT INTO electric(name, billingnumber, email, address, lastreading, currentreading, price, date) VALUES(?,?,?,?,?,?,?,?)");
                        pst.setString(1, Name);
                        pst.setString(2, BillNo);
                        pst.setString(3, Email);
                        pst.setString(4, Address);
                        pst.setString(5, "0");
                        pst.setString(6, "0");
                        pst.setString(7, "0");
                        pst.setString(8, "0");

                        pst.executeUpdate();
                    } catch (SQLException ex) {
                        Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    try {
                        pst = con.prepareStatement("INSERT INTO water(name, billingnumber, email, address, lastreading, currentreading, price, date) VALUES(?,?,?,?,?,?,?,?)");
                        pst.setString(1, Name);
                        pst.setString(2, BillNo);
                        pst.setString(3, Email);
                        pst.setString(4, Address);
                        pst.setString(5, "0");
                        pst.setString(6, "0");
                        pst.setString(7, "0");
                        pst.setString(8, "0");

                        pst.executeUpdate();
                    } catch (SQLException ex) {
                        Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    try {
                        pst = con.prepareStatement("INSERT INTO phone(name, billingnumber, email, address,price, balance) VALUES(?,?,?,?,?,?)");
                        pst.setString(1, Name);
                        pst.setString(2, BillNo);
                        pst.setString(3, Email);
                        pst.setString(4, Address);
                        pst.setString(5, "0");
                        pst.setString(6, Deposit);

                        pst.executeUpdate();
                    } catch (SQLException ex) {
                        Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    try {
                        pst = con.prepareStatement("INSERT INTO electric(name, billingnumber, email, address, lastreading, currentreading, price, date) VALUES(?,?,?,?,?,?,?,?)");
                        pst.setString(1, Name);
                        pst.setString(2, BillNo);
                        pst.setString(3, Email);
                        pst.setString(4, Address);
                        pst.setString(5, "0");
                        pst.setString(6, "0");
                        pst.setString(7, "0");
                        pst.setString(8, "0");

                        pst.executeUpdate();
                    } catch (SQLException ex) {
                        Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    try {
                        pst = con.prepareStatement("INSERT INTO water(name, billingnumber, email, address, lastreading, currentreading, price, date) VALUES(?,?,?,?,?,?,?,?)");
                        pst.setString(1, Name);
                        pst.setString(2, BillNo);
                        pst.setString(3, Email);
                        pst.setString(4, Address);
                        pst.setString(5, "0");
                        pst.setString(6, "0");
                        pst.setString(7, "0");
                        pst.setString(8, "0");

                        pst.executeUpdate();
                    } catch (SQLException ex) {
                        Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_registerActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void gotologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotologinActionPerformed
        new login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gotologinActionPerformed

    private void chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserActionPerformed
        // TODO add your handling code here:
        if (chooser.getSelectedItem().equals("Electric/Water")) {
            deposit.setVisible(false);
            jLabel8.setVisible(false);
        } else {
            deposit.setVisible(true);
            jLabel8.setVisible(true);
        }
    }//GEN-LAST:event_chooserActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField billNo;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> chooser;
    private javax.swing.JTextField deposit;
    private javax.swing.JTextField email;
    private javax.swing.JButton gotologin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton register;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
